- name: Install docker package
  hosts: aws_ec2
  become: true
  vars:
    container_count: 2
    default_container_name: docker
    default_container_image: nginx
    default_container_command: sleep 1d
  tasks:
    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ container_count }}